services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 9tPf5DmJxBPy
    volumes:
      - ./Producer:/usr/local/platform/Producer
      - ./Consumer:/usr/local/platform/Consumer
    working_dir: /usr/local/platform
    networks:
      - app-network

  producer:
    build: producer
    working_dir: '/usr/src/app'
    volumes:
      - './producer:/usr/src/app'
    environment:
      MONGODB_USER: "mongo"
      MONGODB_PASS: "9tPf5DmJxBPy"
      MONGODB_DBNAME: "Producer"
      RABBITMQ_URL: "amqp://rabbitmq"
    depends_on:
      - mongo
      - rabbitmq
    links:
      - mongo
      - rabbitmq
    networks:
      - app-network
    ports:
      - "3000:3000"

  consumer:
    build: consumer
    working_dir: '/usr/src/app'
    volumes:
      - './consumer:/usr/src/app'
    environment:
      MONGODB_USER: "mongo"
      MONGODB_PASS: "9tPf5DmJxBPy"
      MONGODB_DBNAME: "Consumer"
      RABBITMQ_URL: "amqp://rabbitmq"
    depends_on:
      - mongo
      - rabbitmq
    links:
      - mongo
      - rabbitmq
    networks:
      - app-network
    ports:
      - "3001:3001"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
