### create User

POST http://localhost:3001/users
Content-Type: application/json

{
    "firstname": "toto",
    "lastname": "bismuth",
    "email": "test@gmail.com",
    "phone": "0777777777"
}

### get Users

GET http://localhost:3001/users
Content-Type: application/json
