version: "3.6"
services:

  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: elie
      MYSQL_PASSWORD: mypassword

  api:
    build: .
    volumes:
      - './:/home/node/app:rw,consistent'
    working_dir: '/home/node/app'
    command: 'npm start'
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "3001:3001"

volumes:
  db_data:
